# ------------------------------------------------Environment Settings------------------------------------------------#
gpu_id: "0,1,2,3,4,5,6,7"

# -------------------------------------------------Retrieval Settings------------------------------------------------#
# If set the name, the model path will be find in global paths
retrieval_method: "/input2/zhangqi.zq/models/e5-base-v2"  # name or path of the retrieval model. 
index_path: "/input2/zhangqi.zq/Search-R1/e5_Flat.index" # path to the indexed file
faiss_gpu: True # whether use gpu to hold index
corpus_path: "/input2/zhangqi.zq/Search-R1/wiki-18.jsonl"  # path to corpus in '.jsonl' format that store the documentsh to corpus in '.jsonl' format that store the documents
# retrieval_batch_size: 1